# @package _global_
defaults:
  - _self_

openai_api_key:
model_name: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16"
max_context_length: 262144
exllama: False
torch_dtype: bfloat16
attn_implementation: flash_attention_2
enable_thinking: false

system_tag_start: "<|im_start|>system\n"
system_tag_end: "<|im_end|>\n"

user_tag_start: "<|im_start|>user\n"
user_tag_end: "<|im_end|>\n"

ai_tag_start: "<|im_start|>assistant\n"
ai_tag_end: "<|im_end|>\n"

stop_words:
 - "<|im_end|>"
 - "<|endoftext|>"
