defaults:
  - _self_
  - paths: example 
  - model: WizardLM70B
  - planner: GPTOss20BPlanner

pathology: appendicitis
agent: ZeroShot
prompt_template: VANILLA
summarize: True
fewshot: False
include_ref_range: False
bin_lab_results: False
bin_lab_results_abnormal: False
provide_diagnostic_criteria: False
include_tool_use_examples: False
abbreviated: True
self_consistency: False
only_abnormal_labs: False
gpt_oss_reasoning_effort: low
planner_max_steps: 10
planner_temperature: 0.2
planner_top_p: 0.95
judge_temperature: 0.0
sample_n: 0
eval_accuracy: true

seed: 2023
local_logging: True
run_descr:

first_patient:
patient_list_path:
hadm_pickle_path:
ref_ranges_json_path:

order: pli
diagnostic_criteria:

rr_name: RR
diag_crit_writer_openai_api_key:
confirm_diagnosis: False
save_probabilities: False
