# @package _global_
defaults:
  - _self_

planner_openai_api_key:
planner_model_name: "peterhan91/oss-20B-planner"
planner_max_context_length: 16384
planner_exllama: False

planner_system_tag_start: "<|start|>system\n"
planner_system_tag_end: "<|end|>\n"

planner_user_tag_start: "<|start|>user\n"
planner_user_tag_end: "<|end|>\n"

planner_ai_tag_start: "<|start|>assistant\n"
planner_ai_tag_end: "<|end|>\n"

planner_stop_words:
  - "<|end|>"
